from __future__ import annotations

from pathlib import Path

from orchestro.planner import PlanDraft, build_plan_draft, fallback_plan_draft, parse_numbered_steps


# ---------------------------------------------------------------------------
# parse_numbered_steps
# ---------------------------------------------------------------------------

class TestParseNumberedSteps:
    def test_period_delimiter(self):
        text = "1. First step\n2. Second step\n3. Third step"
        steps = parse_numbered_steps(text)
        assert steps == ["First step", "Second step", "Third step"]

    def test_parenthesis_delimiter(self):
        text = "1) Do this\n2) Do that"
        steps = parse_numbered_steps(text)
        assert steps == ["Do this", "Do that"]

    def test_colon_delimiter(self):
        text = "1: Step one\n2: Step two"
        steps = parse_numbered_steps(text)
        assert steps == ["Step one", "Step two"]

    def test_dash_delimiter(self):
        text = "- First\n- Second\n- Third"
        steps = parse_numbered_steps(text)
        assert steps == ["First", "Second", "Third"]

    def test_mixed_delimiters(self):
        text = "1. First\n- Second\n3) Third"
        steps = parse_numbered_steps(text)
        assert len(steps) == 3

    def test_empty_string_returns_empty(self):
        assert parse_numbered_steps("") == []

    def test_blank_lines_skipped(self):
        text = "1. First\n\n2. Second\n\n3. Third"
        steps = parse_numbered_steps(text)
        assert len(steps) == 3

    def test_leading_trailing_whitespace_stripped(self):
        text = "1.   Padded step   "
        steps = parse_numbered_steps(text)
        assert steps == ["Padded step"]

    def test_non_list_lines_ignored(self):
        text = "Here is my plan:\n1. Do this\nSome prose.\n2. Do that"
        steps = parse_numbered_steps(text)
        assert steps == ["Do this", "Do that"]

    def test_empty_step_filtered_out(self):
        text = "1. \n2. Real step"
        steps = parse_numbered_steps(text)
        assert "Real step" in steps
        assert "" not in steps

    def test_semicolon_delimiter(self):
        text = "1:- Step one\n2:- Step two"
        # The regex is "1[\).\:-]" so :- won't match but : does match
        steps = parse_numbered_steps(text)
        # At minimum shouldn't crash
        assert isinstance(steps, list)


# ---------------------------------------------------------------------------
# fallback_plan_draft
# ---------------------------------------------------------------------------

class TestFallbackPlanDraft:
    def test_returns_plan_draft(self):
        draft = fallback_plan_draft(goal="do something", domain=None)
        assert isinstance(draft, PlanDraft)

    def test_has_five_steps(self):
        draft = fallback_plan_draft(goal="do something", domain=None)
        assert len(draft.steps) == 5

    def test_steps_are_tuples(self):
        draft = fallback_plan_draft(goal="do something", domain=None)
        for step in draft.steps:
            assert isinstance(step, tuple)
            assert len(step) == 2

    def test_goal_appears_in_steps(self):
        draft = fallback_plan_draft(goal="build the widget", domain=None)
        combined = " ".join(str(s) for s in draft.steps)
        assert "build the widget" in combined

    def test_domain_hint_in_first_step(self):
        draft = fallback_plan_draft(goal="do task", domain="coding")
        first_detail = draft.steps[0][1]
        assert "coding" in first_detail

    def test_no_domain_no_domain_hint(self):
        draft = fallback_plan_draft(goal="do task", domain=None)
        first_detail = draft.steps[0][1]
        # Should not have stray "None" or "Domain focus: None" text
        assert "None" not in first_detail

    def test_source_is_fallback(self):
        draft = fallback_plan_draft(goal="task", domain=None)
        assert draft.source == "fallback"

    def test_notes_not_empty(self):
        draft = fallback_plan_draft(goal="task", domain=None)
        assert draft.notes

    def test_notes_include_reason_when_provided(self):
        draft = fallback_plan_draft(goal="task", domain=None, reason="backend plan generation failed: boom")
        assert "boom" in draft.notes

    def test_step_titles_not_empty(self):
        draft = fallback_plan_draft(goal="task", domain="devops")
        for title, _ in draft.steps:
            assert title.strip()


# ---------------------------------------------------------------------------
# PlanDraft
# ---------------------------------------------------------------------------

class TestPlanDraft:
    def test_fields(self):
        draft = PlanDraft(
            steps=[("Step 1", "Detail 1"), ("Step 2", None)],
            source="model",
            notes="Generated by backend.",
        )
        assert len(draft.steps) == 2
        assert draft.source == "model"
        assert draft.notes == "Generated by backend."

    def test_steps_with_none_detail(self):
        draft = PlanDraft(steps=[("Step", None)], source="fallback", notes="")
        title, detail = draft.steps[0]
        assert title == "Step"
        assert detail is None


class TestBuildPlanDraft:
    def test_backend_failure_reason_recorded_in_fallback_notes(self, tmp_path: Path):
        class BrokenApp:
            def run(self, request):
                raise RuntimeError("planner backend unavailable")

        draft = build_plan_draft(
            BrokenApp(),
            goal="do work",
            backend_name="broken",
            strategy_name="direct",
            working_directory=tmp_path,
            domain=None,
        )
        assert draft.source == "fallback"
        assert "planner backend unavailable" in draft.notes
